f = open("sample_txt", "r")
text = f.read()
f.close()
lines = text.split('\n')
words = text.split()
chars = len(text)
print("Number of lines:", len(lines))
print("Number of words:", len(words))
print("Number of characters:", chars)